#! /bin/bash

# Create directories
mkdir -p ~/.config
mkdir -p ~/.dwm
mkdir -p ~/.local/bin/statusbar
doas mkdir -p /usr/share/X11/xorg.conf.d/

# zsh / bash
cp .zshenv ~
cp .zshrc ~

# libinput
doas cp -f ./libinput/40-libinput.conf /usr/share/X11/xorg.conf.d/40-libinput.conf

# vim-plug for nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim -c PlugInstall -c qa

# x
cp .xinitrc ~

# tmux
cp .tmux.conf ~

# gitconfig
cp .gitconfig ~

# dwm
cp .dwm/* ~/.dwm

# scripts
cp -r .local/bin/* ~/.local/bin

# config
cp -r .config/* ~/.config
sudo cp ./etc/doas.conf /etc 

# wallpapers
cp -R .backgrounds ~
