#! /bin/bash

# Create directories
mkdir -p ~/.config
mkdir -p ~/.dwm
mkdir -p ~/.local/bin/statusbar

# zsh / bash
cp .zshenv ~
cp .zshrc ~

# vim-plug for nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim -c PlugInstall -c qa
neovim -c OmniSharpInstall -c qa
neovim -c GoInstallBinaries -c qa

# x
cp .xinitrc ~

# dwm
cp .dwm/* ~/.dwm

# scripts
cp -r .local/bin/* ~/.local/bin

# config
cp -r .config/* ~/.config

# wallpapers
cp -R .backgrounds ~
