config_version: 2
settings:
  content.javascript.can_access_clipboard:
    global: true
  downloads.location.directory:
    global: ~/downloads
  downloads.prevent_mixed_content:
    global: false
  scrolling.smooth:
    global: false
  statusbar.show:
    global: always
  tabs.show:
    global: always
  zoom.default:
    global: '100'
